name: simple_speed_dial
description: A speed dial for Flutter.
version: 0.0.1
repository: https://github.com/janoschpelzer/simple_speed_dial

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
